/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MyLib.Dialogs;

import javax.swing.JOptionPane;

/**
 *
 * @author ymnis
 */
public class Register extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        TopRightBorder = new javax.swing.JLabel();
        BottomLeftBorder = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        confirmPassLbl = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        showPassCb2 = new javax.swing.JCheckBox();
        showPassCb1 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        signin = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        confirmPassTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cornerstone Estates | Register");

        logoPanel.setBackground(new java.awt.Color(36, 5, 2));
        logoPanel.setLayout(new java.awt.GridBagLayout());

        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(42, 2, 42, 2);
        logoPanel.add(logo, gridBagConstraints);

        TopRightBorder.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TopRightBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/TR_Border.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        logoPanel.add(TopRightBorder, gridBagConstraints);

        BottomLeftBorder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BottomLeftBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/BL_Border.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        logoPanel.add(BottomLeftBorder, gridBagConstraints);

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        infoPanel.setLayout(jPanel2Layout);

        Header.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Header.setForeground(new java.awt.Color(36, 5, 2));
        Header.setText("Hello!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        infoPanel.add(Header, gridBagConstraints);

        emailLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        emailLbl.setLabelFor(emailTxt);
        emailLbl.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        infoPanel.add(emailLbl, gridBagConstraints);

        passLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        passLbl.setLabelFor(passTxt);
        passLbl.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        infoPanel.add(passLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        infoPanel.add(emailTxt, gridBagConstraints);

        confirmPassLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        confirmPassLbl.setLabelFor(confirmPassTxt);
        confirmPassLbl.setText("Confirm Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        infoPanel.add(confirmPassLbl, gridBagConstraints);

        signupBtn.setBackground(new java.awt.Color(36, 5, 2));
        signupBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("SIGNUP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        infoPanel.add(signupBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        infoPanel.add(jSeparator1, gridBagConstraints);

        showPassCb2.setText("Show Password");
        showPassCb2.addActionListener(this::showPassCb2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(showPassCb2, gridBagConstraints);

        showPassCb1.setText("Show Password");
        showPassCb1.addActionListener(this::showPassCb1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(showPassCb1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(jSeparator2, gridBagConstraints);

        signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin.setText("<html> Already have an account? <b>Sign in </b>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(signin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        infoPanel.add(passTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        infoPanel.add(confirmPassTxt, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPassCb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCb2ActionPerformed
        if (showPassCb2.isSelected()) {
            confirmPassTxt.setEchoChar((char) 0);
        } else {
            confirmPassTxt.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_showPassCb2ActionPerformed

    private void showPassCb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCb1ActionPerformed
        if (showPassCb1.isSelected()) {
            passTxt.setEchoChar((char) 0);
        } else {
            passTxt.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_showPassCb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BottomLeftBorder;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel TopRightBorder;
    private javax.swing.JLabel confirmPassLbl;
    private javax.swing.JPasswordField confirmPassTxt;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JCheckBox showPassCb1;
    private javax.swing.JCheckBox showPassCb2;
    private javax.swing.JLabel signin;
    private javax.swing.JButton signupBtn;
    // End of variables declaration//GEN-END:variables
}
