package MyApp;

import MyLib.Panels.*;
import javax.swing.UIManager;

public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    public AdminDashboard() {
        initComponents();
        
        AdminDashboardPanel Dashboard = new AdminDashboardPanel();
        mainContentPanel.add(Dashboard, "adminDashboard_view");
        
        ClientsPanel clients = new ClientsPanel();
        mainContentPanel.add(clients, "clients_view");
        
        OverviewPanel Properties = new OverviewPanel();
        mainContentPanel.add(Properties, "properties_view");
        
        AnalyticsPanel Analytics = new AnalyticsPanel();
        mainContentPanel.add(Analytics, "analytics_view");
        
        MyAccPanel myAccount = new MyAccPanel();
        mainContentPanel.add(myAccount, "myAcc_view");
    }
    
    
    // HELPERS
    public void showCard(String cardName){
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContentPanel.getLayout();
        cl.show(mainContentPanel, cardName);

        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dashboardBtn = new javax.swing.JButton();
        propertiesBtn = new javax.swing.JButton();
        analyticsBtn = new javax.swing.JButton();
        myAccBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        clientsBtn = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        sidePanel.setBackground(new java.awt.Color(36, 5, 2));
        sidePanel.setPreferredSize(new java.awt.Dimension(200, 475));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Logo.png"))); // NOI18N

        dashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Icons/Dashboard.png"))); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardBtn.setIconTextGap(10);
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);

        propertiesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        propertiesBtn.setForeground(new java.awt.Color(255, 255, 255));
        propertiesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Icons/Overview.png"))); // NOI18N
        propertiesBtn.setText("Properties");
        propertiesBtn.setContentAreaFilled(false);
        propertiesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        propertiesBtn.setIconTextGap(10);
        propertiesBtn.addActionListener(this::propertiesBtnActionPerformed);

        analyticsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        analyticsBtn.setForeground(new java.awt.Color(255, 255, 255));
        analyticsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Icons/Reports.png"))); // NOI18N
        analyticsBtn.setText("Analytics");
        analyticsBtn.setContentAreaFilled(false);
        analyticsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        analyticsBtn.setIconTextGap(10);
        analyticsBtn.addActionListener(this::analyticsBtnActionPerformed);

        myAccBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        myAccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Icons/Account.png"))); // NOI18N
        myAccBtn.setText("My Account");
        myAccBtn.setContentAreaFilled(false);
        myAccBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myAccBtn.setIconTextGap(10);
        myAccBtn.addActionListener(this::myAccBtnActionPerformed);

        clientsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        clientsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Icons/Clients.png"))); // NOI18N
        clientsBtn.setText("Clients");
        clientsBtn.setContentAreaFilled(false);
        clientsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientsBtn.setIconTextGap(10);
        clientsBtn.addActionListener(this::clientsBtnActionPerformed);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(analyticsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(clientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propertiesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(analyticsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(myAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        showCard("adminDashboard_view");
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void propertiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesBtnActionPerformed
        showCard("properties_view");
    }//GEN-LAST:event_propertiesBtnActionPerformed

    private void analyticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsBtnActionPerformed
        showCard("analytics_view");
    }//GEN-LAST:event_analyticsBtnActionPerformed

    private void myAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccBtnActionPerformed
        showCard("myAcc_view");
    }//GEN-LAST:event_myAccBtnActionPerformed

    private void clientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsBtnActionPerformed
        showCard("clients_view");
    }//GEN-LAST:event_clientsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        
        UIManager.put( "Button.arc", 15 );
        UIManager.put( "Component.arc", 15 );
        
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticsBtn;
    private javax.swing.JButton clientsBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JButton myAccBtn;
    private javax.swing.JButton propertiesBtn;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
