package MyApp;

// BUYER PANELS
import MyLib.Panels.SearchPanel;
import MyLib.Panels.OverviewPanel;
import MyLib.Panels.FavoritesPanel;
import MyLib.Panels.MyAccPanel;
import MyLib.Panels.HomePanel;

import javax.swing.UIManager;

public class BuyerDashboard extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuyerDashboard.class.getName());

    public BuyerDashboard() {
        initComponents();
        
        HomePanel Home = new HomePanel();
        mainContentPanel.add(Home, "home_view");
        
        MyAccPanel myAccount = new MyAccPanel();
        mainContentPanel.add(myAccount, "myAcc_view");
        
        OverviewPanel Overview = new OverviewPanel();
        mainContentPanel.add(Overview, "overview_view");
        
        SearchPanel Search = new SearchPanel();
        mainContentPanel.add(Search, "search_view");
        
        FavoritesPanel Favorites = new FavoritesPanel();
        mainContentPanel.add(Favorites, "favorites_view");
        
        
    }
    
    public void showCard(String cardName){
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContentPanel.getLayout();
        cl.show(mainContentPanel, cardName);

        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        homeBtn = new javax.swing.JButton();
        overviewBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        myAccBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        favBtn = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cornerstone Real Estates");
        setExtendedState(6);

        sidePanel.setBackground(new java.awt.Color(36, 5, 2));
        sidePanel.setPreferredSize(new java.awt.Dimension(200, 475));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Logo.png"))); // NOI18N

        homeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Dashboard.png"))); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setContentAreaFilled(false);
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeBtn.setIconTextGap(10);
        homeBtn.addActionListener(this::homeBtnActionPerformed);

        overviewBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        overviewBtn.setForeground(new java.awt.Color(255, 255, 255));
        overviewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Overview.png"))); // NOI18N
        overviewBtn.setText("Overview");
        overviewBtn.setContentAreaFilled(false);
        overviewBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        overviewBtn.setIconTextGap(10);
        overviewBtn.addActionListener(this::overviewBtnActionPerformed);

        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setContentAreaFilled(false);
        searchBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchBtn.setIconTextGap(10);
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        myAccBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        myAccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Account.png"))); // NOI18N
        myAccBtn.setText("My Account");
        myAccBtn.setContentAreaFilled(false);
        myAccBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myAccBtn.setIconTextGap(10);
        myAccBtn.addActionListener(this::myAccBtnActionPerformed);

        favBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        favBtn.setForeground(new java.awt.Color(255, 255, 255));
        favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLib/Images/Favorites.png"))); // NOI18N
        favBtn.setText("Favorites");
        favBtn.setContentAreaFilled(false);
        favBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        favBtn.setIconTextGap(10);
        favBtn.addActionListener(this::favBtnActionPerformed);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(favBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(favBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(myAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainContentPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        showCard("home_view");
    }//GEN-LAST:event_homeBtnActionPerformed

    private void myAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccBtnActionPerformed
        showCard("myAcc_view");
    }//GEN-LAST:event_myAccBtnActionPerformed

    private void overviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewBtnActionPerformed
        showCard("overview_view");
    }//GEN-LAST:event_overviewBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        showCard("search_view");
    }//GEN-LAST:event_searchBtnActionPerformed

    private void favBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favBtnActionPerformed
        showCard("favorites_view");
    }//GEN-LAST:event_favBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        
        UIManager.put( "Button.arc", 15 );
        UIManager.put( "Component.arc", 15 );
        
        java.awt.EventQueue.invokeLater(() -> new BuyerDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton favBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JButton myAccBtn;
    private javax.swing.JButton overviewBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
