package MyLib.Panels;

import MyLib.Classes.Models.Property;
import MyLib.Classes.Services.AuthService;
import MyLib.Dialogs.LotInformation;
import java.awt.Frame;
import java.text.DecimalFormat;
import javax.swing.SwingUtilities;

public class LotReportTemplate extends javax.swing.JPanel {
    
    private final DecimalFormat df = new DecimalFormat("#,##0.00");
    private Property property;
    
    public LotReportTemplate(Property p) {
        initComponents();
        this.property = p;
        
        IDLbl.setText(p.getPropertyID());
        StatusLbl.setText(p.getStatus());
        lotAreaLbl.setText("Lot Area: " + df.format(p.getLotArea()) + " sqm");
        priceLbl.setText("PHP " + df.format(p.calculatePricePerSqFt()));
        AgentLbl.setText(p.getAssignedAgent());
        
        if (p.getStatus().equals("Sold")) StatusLbl.setForeground(java.awt.Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Image1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        houseTypeLbl = new javax.swing.JLabel();
        AgentLbl = new javax.swing.JLabel();
        IDLbl = new javax.swing.JLabel();
        floorAreaLbl = new javax.swing.JLabel();
        StatusLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        DetailsBtn = new javax.swing.JButton();
        lotAreaLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 180));

        Image1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout Image1Layout = new javax.swing.GroupLayout(Image1);
        Image1.setLayout(Image1Layout);
        Image1Layout.setHorizontalGroup(
            Image1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        Image1Layout.setVerticalGroup(
            Image1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0};
        jPanel1.setLayout(jPanel1Layout);

        houseTypeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        houseTypeLbl.setText("House Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 214;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(houseTypeLbl, gridBagConstraints);

        AgentLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        AgentLbl.setText("No Agent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(AgentLbl, gridBagConstraints);

        IDLbl.setText("Block 0 Lot 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(IDLbl, gridBagConstraints);

        floorAreaLbl.setText("Floor Area: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(floorAreaLbl, gridBagConstraints);

        StatusLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        StatusLbl.setText("Available");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(StatusLbl, gridBagConstraints);

        priceLbl.setText("PHP 0.00");
        priceLbl.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(priceLbl, gridBagConstraints);

        DetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DetailsBtn.setText("View Details ");
        DetailsBtn.addActionListener(this::DetailsBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(DetailsBtn, gridBagConstraints);

        lotAreaLbl.setText("Lot Area:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(lotAreaLbl, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsBtnActionPerformed
        Frame parent = (java.awt.Frame) SwingUtilities.getWindowAncestor(this);
        String role = AuthService.getCurrentUser().getRole();
        new LotInformation(parent, true, property, role).setVisible(true);
    }//GEN-LAST:event_DetailsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgentLbl;
    private javax.swing.JButton DetailsBtn;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JPanel Image1;
    private javax.swing.JLabel StatusLbl;
    private javax.swing.JLabel floorAreaLbl;
    private javax.swing.JLabel houseTypeLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lotAreaLbl;
    private javax.swing.JLabel priceLbl;
    // End of variables declaration//GEN-END:variables
}
